apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui
spec:
  selector:
    matchLabels:
      app: kanban-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      containers:
        - name: kanban-ui
          image: bharathvelisala/challenge-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m

---

apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:                     
  name: clinet   # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: clinet     # Name of the kubernetes resource
spec:
    type: LoadBalancer               # Exposes the service by opening a port on each node
    selector:
      app: kanban-ui    # Any Pod matching the label `app=polling-app-client` will be picked up by this service
    ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
    - name: http
      port: 80
      targetPort: 80